### ISSUE TITLE
[BUG] pip install fails on Python 3.7

### ISSUE THREAD

**Issue by karolyjozsa** [bczsalba/pytermgui#71]
**Describe the bug**
pip installation of PyTermGUI version 4 and above fails on earlier versions than Python 3.8.

**To Reproduce**

1. Have a Python 3.7
2. pip install pytermgui
3. error:
```
...pytermgui\terminal.py", line 15, in <module>
from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (c:\users\...\python\python37\lib\functools.py)
```
`pip install pytermgui=3.2.1` is the last that works on Python 3.7

**Possible cause**
functools only introduced cached_property in Python 3.8.

**Possible solution**
Only use this caching if the installed Python is at least 3.8.
Or, you can change the docs to indicate 3.8+ instead of 3.7+

**Comment by bczsalba** [comment]
I've updated `pyproject.toml` to require `3.8`, after a lot of consideration. There is just too many things I rely on having that don't yet exist in `3.7`, sadly :(

Version `7.0.0` (upcoming) will be the first to officially require `3.8`, but as you said `3.2.1` is the last properly supported version.

Thank you for the report!
